name: Upload to Pastebin
on:
  push:
    branches: [main]
jobs:
  pastebin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
      - name: List new files
        id: files
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD~1..HEAD)
          new_files=$(echo "${changed_files}" | grep '^scripts/')
          echo "::set-output name=files::$new_files"
      - name: Upload files to Pastebin
        id: upload
        run: |
          urls=""
          for file in ${{ steps.files.outputs.files }}; do
            paste_url=$(curl -X POST -H "Content-Type: application/json" -d '{"api_dev_key": "${{ secrets.PASTEBIN_API_KEY }}", "api_option": "paste", "api_paste_name": "'"$file"'", "api_paste_code": "$(cat '$file')"}' https://pastebin.com/api/api_post.php | jq -r '.[].url')
            urls="$urls\n- [$file]($paste_url)"
          done
          echo "::set-output name=urls::$urls"
      - name: Update README
        if: success()
        run: |
          sed -i "/^## Links/,\$d" README.md
          echo "## Links\n" >> README.md
          echo -e "${{ steps.upload.outputs.urls }}" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new Pastebin links" -a
          git push
