name: Upload to Pastebin
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  pastebin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            script/*.lua

      - name: Upload files to Pastebin
        id: upload
        run: |
          urls = ""
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            file_contents=$(cat $file)
            paste_name=$(basename $file)
            echo "Uploading $paste_name to Pastebin"
            api_key="${{ secrets.PASTEBIN_API_KEY }}"
            response=$(curl -s -X POST https://pastebin.com/api/api_post.php \
              --data-urlencode "api_dev_key=$api_key" \
              --data-urlencode "api_user_key=$user_key" \
              --data-urlencode "api_option=paste" \
              --data-urlencode "api_paste_name=$paste_name" \
              --data-urlencode "api_paste_code=$file_contents" \
              --data-urlencode "api_paste_private=1" \
              --data-urlencode "api_paste_expire_date=N" \
              --data-urlencode "api_paste_format=lua" )
            paste_url= $response
            echo "$response"
            urls+="$paste_name - $paste_url"
            echo "Uploaded $file to $paste_url"
          done
          export urls=$urls
          echo "::set-env name=urls::$urls"

      - name: Update README
        if: success()
        run: |
          echo "$urls"
          echo -e "$urls" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new Pastebin links" -a
          git push
