name: Upload to Pastebin
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  pastebin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
      - name: List new files
        id: files
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r $(git hash-object -t tree /dev/null)..HEAD)
          new_files=$(echo "${changed_files}" | grep -E '^scripts/' | xargs -I{} sh -c 'test -f "{}" && echo "{}"')
          echo "::set-output name=files::$new_files"
      - name: Upload files to Pastebin
        id: upload
        run: |
          find scripts/ -type f -name '*.lua' -print | while IFS= read -r -d '' file; do
            file_contents=$(cat "$file")
            paste_name=$(basename "$file")
            api_key="${{ secrets.PASTEBIN_API_KEY }}"
            response=$(curl -s -X POST https://pastebin.com/api/api_post.php \
              --data-urlencode "api_dev_key=$api_key" \
              --data-urlencode "api_user_key=$user_key" \
              --data-urlencode "api_option=paste" \
              --data-urlencode "api_paste_name=$paste_name" \
              --data-urlencode "api_paste_code=$file_contents" \
              --data-urlencode "api_paste_private=1" \
              --data-urlencode "api_paste_expire_date=N" \
              --data-urlencode "api_paste_format=lua" )
            paste_url=response
            echo "$response"
            urls="$urls\n- [$paste_name]-($paste_url)"
            export urls=$urls
            echo "::set-env name=urls::$urls"
            echo "Uploaded $file to $paste_url"
          done
          echo "found urls: $urls"

      - name: Update README
        if: success()
        run: |
          echo "$urls"
          echo -e "$urls" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new Pastebin links" -a
          git push
